feat: cleancode.md
kamp-us/turkce-odin-project pull request #14
Opened 2023-05-17 19:30 UTC by bsrakts

create

2023-07-15 15:25 UTC, kutaui commented on temel_bilgiler/javascript_temelleri/cleancode.md
> +Bu okuması zor ve kötü görünümlü bir kod örneği:
```suggestion
Bu okuması zor ve kötü görünen bir kod örneği:
```

2023-07-15 15:26 UTC, kutaui commented on temel_bilgiler/javascript_temelleri/cleancode.md
> +İnanın veya inanmayın, her iki fonksiyon da aynı şeyi\(tamamen aynı şekilde!\) yapıyor ve her ikisi de tamamen geçerli kodlar, ancak görüldüğü üzere ikincisi takip etmesi daha kolaydır.Başka birisiyl
```suggestion
İnanın veya inanmayın, her iki fonksiyon da aynı şeyi\(tamamen aynı şekilde!\) yapıyor ve her ikisi de tamamen geçerli kodlar, ancak görüldüğü üzere ikincisini takip etmesi daha kolay.Başka birisiyle ortak bir projede çalıştığınızı ve ilk fonksiyonu yazdığını hayal edin.. İşinizi yapabilmeniz için ne olup bittiğini anlamalısınız, ilk örnekte bunun için ne kadar süre harcamanız gerekeceğini düşünün. Kendi projenizi yazarken ilk fonksiyonu bir veya iki hafta önce yazdığınızı ve tek başınıza çalıştığınızı düşünün. Tam olarak ne yaptığınızı muhtemelen hatırlamayacaksınız. Her şeyi çözmek ve anlamak için tekrar iyi bir zaman harcamanız gerekecektir.
```

2023-07-15 15:27 UTC, kutaui commented on temel_bilgiler/javascript_temelleri/cleancode.md
> +### Assignment
```suggestion
### Ödev
```

2023-07-15 15:34 UTC, kutaui commented on temel_bilgiler/javascript_temelleri/cleancode.md
> +Gerçekten ikincisi takip etmek için çok daha kolaydır. Kodun içerisindeki her şeyi tam olarak anlamasanız bile değişkenler açıkça isimlendirildiği için tahmin edebilirsiniz.Girintili yazılması da fon
```suggestion
Gerçekten ikincisini takip etmek çok daha kolaydır. Kodun içerisindeki her şeyi tam olarak anlamasanız bile değişkenler açıkça isimlendirildiği için tahmin edebilirsiniz. Girintinin tutarlı kullanımı da fonksiyonun farklı bölümlerini anlaşılabilir kılmaktadır.
```

2023-07-20 17:41 UTC, ubsoydan requested changes
Good one!
Considering this is your first one, hopefully many more will come and will shine! 
Thanks for your contribution Büşra!

2023-07-20 17:41 UTC, ubsoydan commented on temel_bilgiler/javascript_temelleri/cleancode.md
> +Geliştiriciler kod yazmaktan daha çok kod okumaya zaman harcıyorlar. Bu kendi kodunuzda bile doğrudur.Lütfen kendinize ve kodunuzu kullanacak,bakımını yapacak ve geliştirecek kişilere iyilik yapmak i
```suggestion
Geliştiriciler kod yazmaktan daha çok, kod okumaya zaman harcıyorlar. Bu kendi kodunuz için bile geçerlidir. Lütfen kendinize ve kodunuzu kullanacak, bakımını yapacak veya ileride geliştirecek kişilere iyilik yapmak için okunabilir kod yazmayı öğrenin.
```

2023-07-20 17:41 UTC, ubsoydan commented on temel_bilgiler/javascript_temelleri/cleancode.md
> +İnanın veya inanmayın, her iki fonksiyon da aynı şeyi\(tamamen aynı şekilde!\) yapıyor ve her ikisi de tamamen geçerli kodlar, ancak görüldüğü üzere ikincisini takip etmesi daha kolay.Başka birisiyle
```suggestion
İnanın veya inanmayın, her iki fonksiyon da aynı şeyi\(tamamen aynı şekilde!\) yapıyor ve her ikisi de tamamen geçerli kodlar ancak görüldüğü üzere ikincisini takip etmesi daha kolay. Başka birisiyle ortak bir projede çalıştığınızı ve ilk fonksiyonu onun yazdığını hayal edin. İşinizi yapabilmeniz için ne olup bittiğini anlamalısınız, ilk örnekte bunun için ne kadar süre harcamanız gerekeceğini düşünün. Kendi projenizde tek başınıza çalıştığınızı ve bir iki hafta önce ilk örnekteki fonksiyonu yazdığınızı düşünün. Tam olarak ne yaptığınızı muhtemelen hatırlamayacaksınız. Her şeyi çözmek ve anlamak için _yine_ bayağı bir zaman harcamanız gerekecektir.
```

2023-07-20 17:41 UTC, ubsoydan commented on temel_bilgiler/javascript_temelleri/cleancode.md
> +Gerçekten ikincisini takip etmek çok daha kolaydır. Kodun içerisindeki her şeyi tam olarak anlamasanız bile değişkenler açıkça isimlendirildiği için tahmin edebilirsiniz. Girintinin tutarlı kullanımı
```suggestion
İkincisini takip etmek gerçekten çok daha kolaydır. Kodun içerisindeki her şeyi tam olarak anlamasanız bile değişkenler açıkça isimlendirildiği için tahmin edebilirsiniz. Girintinin tutarlı kullanımı da fonksiyonun farklı bölümlerini anlaşılabilir kılmaktadır.
```

2023-07-20 17:41 UTC, ubsoydan commented on temel_bilgiler/javascript_temelleri/cleancode.md
> +Harika bir JavaScript kodunu oluşturma yöntemleri hakkında birçok farklı görüş var. En önemli şey sadece tutarlı olmanızdır. Kodları girintilemek için tab kullanan ve boşluk kullanan kullanıcılar ara
```suggestion
Bir JavaScript kodunu harika kılan şeyin ne olduğu hakkında birçok farklı görüş var. En önemli şey sadece tutarlı olmanızdır. Kodları girintilemek için tab kullanan ve boşluk kullanan kullanıcılar arasındaki savaş o kadar derinleşmiştir ki [artık bir şaka haline gelmiştir](https://www.youtube.com/watch?v=SsoOG6ZeyUI) ancak tutarlı olduğunuz sürece gerçekten hangisini tercih ettiğiniz önemli değil.
```

2023-07-20 17:41 UTC, ubsoydan commented on temel_bilgiler/javascript_temelleri/cleancode.md
> +1.  Girintileme: Kullandığınız girintileme stili gerçekten önemli değil. Farklı JS stil rehberleri farklı seçenekleri önerebilir ve biri diğerinden üstün değildir. Her halükarda önemli olan tutarlılı
```suggestion
1.  Girintileme: Kullandığınız girintileme stili _gerçekten_ önemli değil. Farklı JS stil rehberleri farklı seçenekler önermektedir ve hiçbiri bir diğerinden üstün değildir. Her halükarda önemli olan tutarlılıktır. Alıştırmalarımızda girintileme için 2 boşluk kullanacağız.
```

2023-07-20 17:41 UTC, ubsoydan commented on temel_bilgiler/javascript_temelleri/cleancode.md
> +2.  Noktalı virgüller: Noktalı virgüller, JavaScript'te çoğunlukla isteğe bağlıdır. Çünkü JS derleyicisi atlanmışlarsa otomatik olarak ekleyecektir. Fakat bu fonksiyonalite bazı durumlarda bozulabili
```suggestion
2.  Noktalı virgüller: Noktalı virgüller, JavaScript'te _çoğu zaman_ isteğe bağlıdır. Çünkü eksikse, JS derleyicisi otomatik olarak ekleyecektir. Fakat bu fonksiyonalite bazı durumlarda bozulabilir ve kodunuzda hatalara neden olabilir. Bu yüzden noktalı virgülü eklemeye alışmak daha iyidir. Ekleyin gitsin!
```

2023-07-20 17:41 UTC, ubsoydan commented on temel_bilgiler/javascript_temelleri/cleancode.md
> +3. Satır uzunluğu: Yine farklı stil rehberleri bu konuda farklı önerilerde bulunabilir, ancak neredeyse tümü her satır uzunluğunu sınırlandırmayı önerir. Bu kural diğer kurallar kadar sıkı değildir.
```suggestion
3. Satır uzunluğu: Yine farklı stil rehberleri bu konuda farklı önerilerde bulunabilir ancak neredeyse HEPSİ, satır uzunluğunu sınırlandırmayı önerir. Bu kural diğer kurallar kadar sıkı değildir. Fakat genel bir kural olarak, kodunuzun her satırını yaklaşık 80 karakterden sonra manuel olarak bölmeniz kodunuzu daha okunaklı hale getirir. Birçok kod düzenleyicisi, bu eşiği geçtiğinizde size uyarı verecek bir satır göstergesine sahiptir. Satırları manuel olarak bölerken, operatör veya virgülün hemen sonrasında bölmeniz önerilir. Devam satırlarını düzenlemenin birkaç yolu vardır. Örneğin şunları yapabilirsiniz:
```

2023-07-20 17:41 UTC, ubsoydan commented on temel_bilgiler/javascript_temelleri/cleancode.md
> +   - devam satırlarını aynı seviye girintiyle girintileyin,
```suggestion
   - devam satırlarını bir kez girintileyin.
```

2023-07-20 17:41 UTC, ubsoydan commented on temel_bilgiler/javascript_temelleri/cleancode.md
> +   - devam eden satırları dikey olarak ilk değişkenle hizalayın,
```suggestion
   - devam satırlarını, ilk değişkeni baz alarak dikeylemesine hizalayın
```

2023-07-20 17:41 UTC, ubsoydan commented on temel_bilgiler/javascript_temelleri/cleancode.md
> +   - veya tamamen farklı bir biçim kullanabilirsiniz. Kurallar katı değildir ve iş ortamından iş ortamına değişkenlik gösterebilir, yine de tutarlı olmaya dikkat edin.
```suggestion
   - veya tamamen farklı bir biçim kullanabilirsiniz. Kurallar katı değildir ve iş ortamından iş ortamına değişkenlik gösterebilir, yeter ki tutarlı olmaya dikkat edin.
```

2023-07-20 17:41 UTC, ubsoydan commented on temel_bilgiler/javascript_temelleri/cleancode.md
> +4.  Fonksiyonları ve Değişkenleri isimlendirme: Fonksiyonlar ve değişkenler için isimlendirme açık olmalıdır. Her zaman camelCase kullanın. Tutarlılık ve okunabilirlik için değişkenler her zaman bir
```suggestion
4.  Fonksiyonları ve Değişkenleri İsimlendirme: Fonksiyonlar ve değişkenler için isimlendirme açık olmalıdır. Her zaman camelCase kullanın. Tutarlılık ve okunabilirlik için değişkenler her zaman bir isim veya sıfatla (yani bir tamlama oluşturmalı) başlamalı ve fonksiyonlar bir fiil ile başlamalıdır. Döngü veya callback fonksiyonu bağlamında tek karakterli değişken adları kullanmak sorun değil ama başka yerlerde kullanmamaya özen gösterin.
```

2023-07-20 17:41 UTC, ubsoydan commented on temel_bilgiler/javascript_temelleri/cleancode.md
> +1.  [Bu temiz kod ipuçlarının listesi](https://onextrapixel.com/10-principles-for-keeping-your-programming-code-clean/).
```suggestion
1.  [Temiz koda dair ipucu listesi](https://onextrapixel.com/10-principles-for-keeping-your-programming-code-clean/).
```

2023-07-20 17:41 UTC, ubsoydan commented on temel_bilgiler/javascript_temelleri/cleancode.md
> +2.  [Makale](https://blog.codinghorror.com/coding-without-comments/), [Diğer makale](https://blog.codinghorror.com/code-tells-you-how-comments-tell-you-why/) kodunuzda yorumların rolü içi bu makalele
```suggestion
2.  [Bu makale](https://blog.codinghorror.com/coding-without-comments/) ve [bir de bu makale](https://blog.codinghorror.com/code-tells-you-how-comments-tell-you-why/) kodunuzdaki yorumların önemini anlatmaktadır.
```

2023-07-20 17:41 UTC, ubsoydan commented on temel_bilgiler/javascript_temelleri/cleancode.md
> +- [Önceden bahsedilen 5 temiz kod yazma prensibini adlandırın.](https://onextrapixel.com/10-principles-for-keeping-your-programming-code-clean/)
```suggestion
- [Önceden bahsedilen 5 temiz kod yazma prensibini sayın](https://onextrapixel.com/10-principles-for-keeping-your-programming-code-clean/)
```

2023-07-20 17:41 UTC, ubsoydan commented on temel_bilgiler/javascript_temelleri/cleancode.md
> +- [İyi yorumlar ve kötü yorumların farklılıkları nedir?](https://onextrapixel.com/10-principles-for-keeping-your-programming-code-clean/)
```suggestion
- [İyi ve kötü yorumların arasındaki farklar nelerdir?](https://onextrapixel.com/10-principles-for-keeping-your-programming-code-clean/)
```

2023-07-20 17:41 UTC, ubsoydan commented on temel_bilgiler/javascript_temelleri/cleancode.md
> +Bu bölüm, ilgili içeriğe yönlendiren yararlı bağlantılar içerir. Zorunlu değildir, dolayısıyla ek olarak düşünülebilir.
```suggestion
Bu alanda içerikle alakalı faydalı linkler bulunmaktadır. Zorunlu değildir, ek olarak düşünülmelidir.
```

2023-07-20 17:41 UTC, ubsoydan commented on temel_bilgiler/javascript_temelleri/cleancode.md
> +* Tam rehber: [kendini belgeleyen kodlarla](http://wiki.c2.com/?SelfDocumentingCode)
```suggestion
* ["Kendi kendini açıklayan kod" rehberi](http://wiki.c2.com/?SelfDocumentingCode)
```

2023-07-20 17:41 UTC, ubsoydan commented on temel_bilgiler/javascript_temelleri/cleancode.md
> +* [Cümleler yazmak için yöntem zincirleme](https://web.archive.org/web/20190211152543/https://javascriptissexy.com/beautiful-javascript-easily-create-chainable-cascading-methods-for-expressiveness/)
```suggestion
* [Cümle yazmak için zincirleme yöntemini kullanmak](https://web.archive.org/web/20190211152543/https://javascriptissexy.com/beautiful-javascript-easily-create-chainable-cascading-methods-for-expressiveness/)   
```

2023-07-27 09:03 UTC, merged