Translate temel_bilgiler/git/temel_git
kamp-us/turkce-odin-project pull request #25
Opened 2023-07-14 22:13 UTC by kutaui

2023-07-15 19:55 UTC, kutaui commented on temel_bilgiler/git/temel_git/git_giriş.md
> +Bu bölüm, ilgili içerik için yararlı bağlantılar içerir. Zorunlu değildir, bu nedenle yardımcı olarak kabul edin.
```suggestion
Bu alanda içerikle alakalı faydalı linkler bulunmaktadır. Zorunlu değildir, ek olarak düşünülmelidir.
```

2023-07-15 19:55 UTC, kutaui commented on temel_bilgiler/git/temel_git/temel_git.md
> +Bu bölüm, ilgili içerik için yararlı bağlantılar içerir. Zorunlu değildir, bu nedenle yardımcı olarak kabul edin.
```suggestion
Bu alanda içerikle alakalı faydalı linkler bulunmaktadır. Zorunlu değildir, ek olarak düşünülmelidir.
```

2023-07-15 19:56 UTC, kutaui commented on temel_bilgiler/git/temel_git/temel_git.md
> +Bu bölüm, bu derste öğreneceğiniz konulara genel bir bakış içermektedir.
```suggestion
Bu bölüm, bu derste öğreneceğiniz konuların genel bir özetini içerir.
```

2023-07-15 19:56 UTC, kutaui commented on temel_bilgiler/git/temel_git/git_giriş.md
> +Bu bölüm, bu derste öğreneceğiniz konulara genel bir bakış içermektedir.
```suggestion
Bu bölüm, bu derste öğreneceğiniz konuların genel bir özetini içerir.
```

2023-08-10 12:47 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/git_giriş.md
> +Git, dosyalarınız ve dizinleriniz için **epik bir kaydetme düğmesi** gibidir. Resmi olarak Git bir sürüm kontrol sistemidir.
```suggestion
Git, dosyalarınız ve dizinleriniz için **müthiş bir kaydetme düğmesi** gibidir. Git, resmi adıyla bir sürüm kontrol sistemidir.
```

2023-08-10 12:49 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/git_giriş.md
> +<span id="text-editor-and-git"></span>Bir metin düzenleyicide yapılan _kaydetme_ işlemi, bir belgedeki tüm sözcükleri tek bir dosya olarak kaydeder. Yinelenen kopyalar yapmadığınız sürece `makale.doc
```suggestion
<span id="text-editor-and-git"></span>Bir metin düzenleyicide yapılan _kaydetme_ işlemi, bir belgedeki tüm sözcükleri tek bir dosya olarak kaydeder. Kopyalarını oluşturmadığınız sürece `makale.doc` gibi, dosyanın yalnızca tek bir kaydı verilir (ve birden fazla kopya yapmayı hatırlamak ve takip etmek zordur):
```

2023-08-10 12:51 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/git_giriş.md
> +Fakat Git'teki bir _kayıt_, dosya ve klasörlerdeki farklılıkları kaydeder VE **her kaydın geçmiş kaydını** tutar. Bu çığar açıcı özellik, bireysel bir geliştirici olarak projenizin nasıl büyüdüğünü g
```suggestion
Fakat Git'teki bir _kaydetme işlemi_, dosya ve klasörlerdeki farklılıkları kaydeder VE **her kaydetme işleminin geçmiş kaydını** tutar. Bu çığır açıcı özellik, bir geliştirici olarak projenizin nasıl büyüdüğünü gözden geçirmenize ve geçmişteki dosya durumlarına kolayca bakmanıza veya geri yüklemenize olanak tanır. Bir ağa bağlandıktan sonra Git, projenizi GitHub'a veya Bitbucket, Beanstalk veya GitLab gibi diğer alternatiflere yüklemenize olanak tanır. Bu, projenizi başkalarıyla paylaşmanızı ve işbirliği yapmanızı kolaylaştırır.
```

2023-08-10 12:55 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/git_giriş.md
> +Bir sonraki derste, Git'i kullanmak için temel iş akışının üzerinden geçeceğiz, bu daha da iyi anlamanızı sağlayacak ve Git'in neden bu kadar yararlı olduğunu gösterecektir.
```suggestion
Bir sonraki derste, Git'i kullanmak için temel iş akışının üzerinden geçeceğiz, bu Git'i daha da iyi anlamanızı sağlayacak ve Git'in neden bu kadar yararlı olduğunu gösterecektir.
```

2023-08-10 12:56 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/git_giriş.md
> +Şimdilik Git'in ne olduğunu ve neden bu kadar güçlü olduğunu öğrenelim!
```suggestion
Şimdiyse, Git'in ne olduğunu ve neden bu kadar güçlü olduğunu öğrenelim!
```

2023-08-10 12:58 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/git_giriş.md
> +- Git ile bir metin editörü arasındaki farkları, kaydettikleri ve kayıt tuttukları farklılıklar açısından açıklayın.
```suggestion
- Git ile bir metin editörü arasındaki farkları, neyi kaydettiklerini ve neyin kaydını tuttuklarının farklarını açıklayın.
```

2023-08-10 13:01 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/git_giriş.md
> +5. Tüm derslerin saklandığı The Odin Project'in kendi [GitHub deposuna](https://github.com/TheOdinProject/curriculum) bir göz atın. Oradayken, tüm [katkıda bulunanlarımıza](https://github.com/TheOdin
```suggestion
5. Tüm derslerin saklandığı The Odin Project'in kendi [GitHub deposuna](https://github.com/TheOdinProject/curriculum) bir göz atın. Oradayken, tüm [katkıda bulunanlarımıza](https://github.com/TheOdinProject/curriculum/graphs/contributors) bakın ve Git'in tüm işbirlikçilerin çabalarını nasıl kaydettiğini ve GitHub'un bunu nasıl görselleştirdiğine dikkat edin.
```

2023-08-10 13:03 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +- GitHub'a dosya yükleme ve alma.
```suggestion
- GitHub'a dosya yükleme ve GitHub'dan dosya indirme.
```

2023-08-10 13:05 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +- Github kısa süre önce varsayılan dal adını değiştirdi. Bu yüzden git sürümünüzün yeni olduğundan emin olun (2.28 ya da
```suggestion
- Github kısa süre önce varsayılan branch adını (dal) değiştirdi. Bu yüzden git sürümünüzün yeni olduğundan emin olun (2.28 ya da
```

2023-08-10 13:07 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +   oluşturmuş olmalısınız. Eğer oluşturmadıysanız, [burdan](https://github.com/) oluşturun.
```suggestion

```

2023-08-10 13:10 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +1. [Git Kurulumu](https://www.theodinproject.com/lessons/foundations-setting-up-git) dersinde bir GitHub hesabı
```suggestion
1. [Git Kurulumu](https://www.theodinproject.com/lessons/foundations-setting-up-git) dersinde bir GitHub hesabı oluşturmuş olmalısınız. Eğer oluşturmadıysanız, [buradan](https://github.com/) oluşturun.
```

2023-08-10 13:13 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +   ardından sayfanın altındaki "Depo oluştur" düğmesine tıklayarak depoyu oluşturun .
```suggestion
```

2023-08-10 13:13 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +3. `Repository name` kısmından, depo adınıza "git_test" ismini verin."Add a README file" kutucuğunu işaretleyin. Ve
```suggestion
3. `Repository name` kısmından, depo adınıza "git_test" ismini verin."Add a README file" kutucuğunu işaretleyin. Ve ardından sayfanın altındaki "Depo oluştur" düğmesine tıklayarak depoyu oluşturun .
```

2023-08-10 13:14 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +4. Bu sizi GitHub'daki yeni deponuza yönlendirecektir. Bu depoyu yerel makinenize kopyalamak (klonlamak) için, yeşil "
```suggestion
4. Bu sizi GitHub'daki yeni deponuza yönlendirecektir. Bu depoyu yerel makinenize kopyalamak (klonlamak) için, yeşil "Code" düğmesine tıklayın. Ardından SSH seçeneğini seçin ve altındaki satırı kopyalayın. **NOT: Doğru URL'yi almak için SSH seçeneğine tıklamalısınız.**
```

2023-08-10 13:14 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +   Code" düğmesine tıklayın. Ardından SSH seçeneğini seçin ve altındaki satırı kopyalayın. **NOT: Doğru URL'yi almak
```suggestion
```

2023-08-10 13:14 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +   için SSH seçeneğine tıklamalısınız.**
```suggestion
```

2023-08-10 13:17 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +5. Tüm Odin projeleriniz için yeni bir dizin oluşturmak için yerel makinenizdeki komut satırını kullanalım. Ana
```suggestion
5. Tüm Odin projeleriniz için yeni bir dizin oluşturmak için yerel makinenizdeki komut satırını kullanalım. Ana klasörünüzde `mkdir` komutu ile `repos` adında bir dizin oluşturun. Ana klasörünüz `~` işareti ile temsil edilir.
```

2023-08-10 13:17 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +   klasörünüzde `mkdir` komutu ile `repos` adında bir dizin oluşturun. Ana klasörünüz `~` işareti ile temsil
```suggestion
```

2023-08-10 13:20 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +   edilir. [Navigating Files and Directories](https://swcarpentry.github.io/shell-novice/02-filedir.html#callout1) bazı
```suggestion
   [Dosya ve Dizinlerde Gezinme](https://swcarpentry.github.io/shell-novice/02-filedir.html#callout1) bazı ana klasör varyasyonlarını göstermektedir - bazı zamanlar `~`, `/users/sizin_adınız` yerine geçer ya da `/home/sizin_adınız`. Eğer ana klasörünüzde olduğunuzdan emin değilseniz, `cd ~` komutunu yazın. Klasör oluşturulduktan sonra, `cd` komutunu kullanarak klasöre geçin.
```

2023-08-10 13:20 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +   ana klasör varyasyonlarını göstermektedir - bazı zamanlar `~`, `/Users/your_username` yerine geçer, ya
```suggestion
```

2023-08-10 13:20 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +   da `/home/your_username`. Eğer ana klasörünüzde olduğunuzdan emin değilseniz, `cd ~` komutunu yazın. Klasör
```suggestion
```

2023-08-10 13:20 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +   oluşturulduktan sonra, `cd` komutunu kullanarak klasöre geçin.
```suggestion
```

2023-08-10 13:22 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +7. <span id="origin-push"></span>Bu kadar! GitHub da açtığınız deponuzu başarılı bir şekilde bilgisayarınıza bağladınız.
```suggestion
7. <span id="origin-push"></span>Bu kadar! GitHub'da açtığınız deponuzu başarılı bir şekilde bilgisayarınıza bağladınız.
```

2023-08-10 13:23 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +   ardından `git remote -v` komutunu çalıştırın. Bu komut GitHub depo URL
```suggestion
   ardından `git remote -v` komutunu çalıştırın. Bu komut GitHub depo URL'sini
```

2023-08-10 13:23 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +   dikkatinizi çekmiş olabilir, uzaktan bağlantınızın adını temsil eder. **origin** ismi uzaktan depolara verilen hem
```suggestion
   dikkatinizi çekmiş olabilir, uzaktan bağlantınızın adını temsil eder. **Origin** ismi uzaktan depolara verilen hem
```

2023-08-10 13:25 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +   kırmızı olarak gözükmektedir. , bunun anlamı dosyanın hazırlanmamış(unstaged) olmasıdır.
```suggestion
   kırmızı olarak gözükmektedir. , bunun anlamı dosyanın işaretlenmemiş (unstaged) olmasıdır.
```

2023-08-10 13:27 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +   hello_world.txt dosyanızı Git'in hazırlanma(staged) bölgesine ekler. Hazırlanma(staging) bölgesi, iki aşamadan
```suggestion
   hello_world.txt dosyanızı Git'in işaretlenmişler (staged) kısmına ekler. İşaretlenmişler (staging) kısmı, iki aşamadan
```

2023-08-10 13:28 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +   oluşan, Git'te bir işlem(commit) yapmanın parçasıdır. Hazırlanma(staging) bölgesini, değiştirdiğiniz dosyaların Git
```suggestion
   oluşan, Git'te bir işlem(commit) yapmanın parçasıdır. İşaretleme (staging) kısmını, değiştirdiğiniz dosyaların Git
```

2023-08-10 13:29 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +   dosyanız yeşil olarak gözüküyor, bu da dosyanın hazırlanma(staging) bölgesinde olduğunu gösteriyor.
```suggestion
   dosyanız yeşil olarak gözüküyor, bu da dosyanın işaretleme (staging) bölgesinde olduğunu gösteriyor.
```

2023-08-10 13:30 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +   ettiğiniz taktir de çözülecektir.
```suggestion
   ettiğiniz takdirde çözülecektir.
```

2023-08-10 13:31 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +4. README.md dosyasını hazırlanma(staging) bölgesine eklemek için `git add README.md` yazın.
```suggestion
4. README.md dosyasını işaretleme (staging) bölgesine eklemek için `git add README.md` yazın.
```

2023-08-10 13:34 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +Github üzerinden yapmaya çalışabilirsiniz. Ancak, bu, bu aşamada üzerinde durmak istemediğimiz daha gelişmiş Git bilgisi
```suggestion
Github üzerinden yapmaya çalışabilirsiniz. Ancak bu durum, bu aşamada üzerinde durmak istemediğimiz daha gelişmiş Git bilgisi
```

2023-08-10 13:35 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +taahhüt etmeniz önerilir.
```suggestion
yüklemeniz etmeniz önerilir.
```

2023-08-10 13:35 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +Bu bir referans listesidir. En sık kullanılan Git komutlarının bir listesidir. (Bu kullanışlı sayfayı yer imlerinize
```suggestion
Bu liste en sık kullanılan Git komutlarının bir listesidir. (Bu kullanışlı sayfayı yer imlerinize
```

2023-08-10 13:36 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +Git basit sözdizimi `program | aksiyon | hedef`.
```suggestion
Git komutlarının mantığı kısaca `program | aksiyon | hedef` şeklindedir.
```

2023-08-10 13:37 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +Git kullanımı hakkında öğrenebileceğiniz çok şey var. Ancak, daha iyi bir işbirlikçi olmanız için bazı en iyi
```suggestion
Git kullanımı hakkında öğrenebileceğiniz çok şey var. Ancak daha iyi bir işbirlikçi olmanız için bazı iyi
```

2023-08-10 13:37 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +uygulamaları öğrenmelisiniz. Git, yalnızca diğerleriyle işbirliği yaparken değil, aynı zamanda bağımsız olarak
```suggestion
pratikleri öğrenmelisiniz. Git, yalnızca diğerleriyle işbirliği yaparken değil, aynı zamanda bağımsız olarak
```

2023-08-10 13:38 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +İki yardımcı en iyi uygulama **atomik işlemler** ve bu atomik işlemleri kullanarak işlemlerinizin(commit) gelecekteki
```suggestion
Faydalı olabilecek bir pratik örneği, **atomik işlemler** ve bu atomik işlemleri kullanarak işlemlerinizin(commit) gelecekteki
```

2023-08-10 13:39 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +diğer değişiklikleri kaybetmeden belirli değişikliği geri almak kolaydır; ve ikinci olarak, daha iyi bir işlem(commit)
```suggestion
diğer değişiklikleri kaybetmeden belirli değişikliği geri almak kolaydır; ikinci olarak, daha iyi bir işlem(commit)
```

2023-08-10 13:48 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +Yanlışlıkla bayrağı atladığınızda, varsayılan mesaj editörünü değiştirmek, eğer Vim kullanmayı tercih etmiyorsanız iyi
```suggestion
Mesaj bayrağını kullanmayı unutuyorsanız ve Vim kullanmak gibi bir niyetiniz yoksa, varsayılan mesaj düzenleyicinizi VSCode olarak değiştirmek iyi bir fikir olabilir.
```

2023-08-10 13:49 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +Bunu değiştirmenin bir dezavantajı yoktur, çünkü işleme(commit) mesajlarınızı terminalde veya VS Code da yazma
```suggestion
Bunu değiştirmenin bir dezavantajı yoktur çünkü işleme (commit) mesajlarınızı ister terminalde isterseniz de VSCode'da yazma
```

2023-08-10 13:51 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +bayrağını (`-m`) kullanmadan kullandığınızda [Vim](<https://en.wikipedia.org/wiki/Vim_(text_editor)>) ile commit
```suggestion
bayrağı (`-m`) ile [Vim](<https://en.wikipedia.org/wiki/Vim_(text_editor)>)'de commit mesajı yazmak zorunda kalmayacağınız bir yöntem mevcut.
```

2023-08-10 13:51 UTC, ubsoydan commented on temel_bilgiler/git/temel_git/temel_git.md
> +mesajınızı yazmak zorunda kalmayacaksınız.
```suggestion
```

2023-08-10 13:58 UTC, ubsoydan requested changes
Excellent work Kutay!
This must have been a brain-frier for you. It seems like you have done very well.

One little issue about paragraphs, though. "git_basics" file has lots of unnecessary line breaks that will have negative impact on readability in the future. I've done a few corrections to make my point as seen on lines 46, 47 and 48. Can you fix other ones as well before committing again?

Thanks for your effort! It is well worth.

2023-08-13 19:06 UTC, cansirin commented on temel_bilgiler/git/temel_git/temel_git.md
> +Mesaj bayrağını kullanmayı unutuyorsanız ve Vim kullanmak gibi bir niyetiniz yoksa, varsayılan mesaj düzenleyicinizi VSCode olarak değiştirmek iyi bir seçenek olabilir.
```suggestion
Mesaj yazmayı unutuyorsanız ve Vim kullanmak gibi bir niyetiniz yoksa, varsayılan mesaj düzenleyicinizi VSCode olarak değiştirmek iyi bir seçenek olabilir.
```

2023-08-13 19:07 UTC, cansirin commented on temel_bilgiler/git/temel_git/temel_git.md
> +- Github kısa süre önce varsayılan branch adını (dal) değiştirdi. Bu yüzden git sürümünüzün yeni olduğundan emin olun (2.28 ya da sonrası). Git sürümünüzü kontrol etmek için `git --version` komutunu
```suggestion
- Github kısa süre önce varsayılan branch (dal) adını değiştirdi. Bu yüzden git sürümünüzün yeni olduğundan emin olun (2.28 ya da sonrası). Git sürümünüzü kontrol etmek için `git --version` komutunu kullanabilirsiniz.
```

2023-08-13 20:45 UTC, merged