Command line basics translation
kamp-us/turkce-odin-project pull request #26
Opened 2023-07-14 22:19 UTC by durmusrasit

2023-07-15 14:51 UTC, kutaui commented on temel_bilgiler/kurulumlar/komut_satiri_temelleri.md
> +Bu bölüm, bu dersi kendi başınıza anlayıp anlamadığınızı kontrol etmeniz için sorular içermektedir. Bir soruyu yanıtlamakta zorlanıyorsanız, soruya tıklayın ve bağlantı verdiği materyali gözden geçir
```suggestion
Bu bölüm, bu dersi kendi başınıza anlayıp anlamadığınızı kontrol etmeniz için sorular içermektedir. Bir soruyu yanıtlamakta zorlanıyorsanız, soruya tıklayın ve bağlantı verdiği materyali gözden geçirin.
```

2023-07-15 14:56 UTC, kutaui commented on temel_bilgiler/kurulumlar/komut_satiri_temelleri.md
> +Bu bölüm, bu dersi kendi başınıza anlayıp anlamadığınızı kontrol etmeniz için sorular içermektedir. Bir soruyu yanıtlamakta zorlanıyorsanız, soruya tıklayın ve bağlantı verdiği materyali gözden geçir
```suggestion
Bu bölüm, bu dersi kendi başınıza anlayıp anlamadığınızı kontrol etmeniz için sorular içermektedir. Bir soruyu yanıtlamakta zorlanıyorsanız, soruya tıklayın ve yönlendirdiği materyali gözden geçirin.
```

2023-07-17 08:38 UTC, durmusrasit commented on temel_bilgiler/kurulumlar/komut_satiri_temelleri.md
> +Bu bölüm, bu dersi kendi başınıza anlayıp anlamadığınızı kontrol etmeniz için sorular içermektedir. Bir soruyu yanıtlamakta zorlanıyorsanız, soruya tıklayın ve bağlantı verdiği materyali gözden geçir
Thanks for the suggestion!

2023-08-17 00:20 UTC, ubsoydan requested changes
Excellent work Raşit!

CLI is the most obscure yet fun to tinker with.
May the CLI be with us!

Thanks a lot!

2023-08-17 00:20 UTC, ubsoydan commented on temel_bilgiler/kurulumlar/komut_satiri_temelleri.md
> +Komut satırından korkuyor musunuz? Yalnız değilsiniz. Şirketin ana bilgisayarını hacklemek için çılgınca anlaşılmaz komutlar girerken, beyaz veya yeşil metinlerin yanıp söndüğü siyah bir ekrana dikka
```suggestion
Komut satırından korkuyor musunuz? Yalnız değilsiniz. Aklımızda, şirketin ana bilgisayarını hacklemek için çılgınca anlaşılmaz komutlar girerken, beyaz veya yeşil metinlerin yanıp söndüğü siyah bir ekrana dikkatle bakan geliştiricilerin imajı canlanıyor.
```

2023-08-17 00:20 UTC, ubsoydan commented on temel_bilgiler/kurulumlar/komut_satiri_temelleri.md
> +Bu siyah ekran veya pencere, bilgisayarınızın sizin için çalıştıracağı komutları girebileceğiniz <span id="command-line">komut satırı arayüzüdür (CLI)</span>. Komut satırıyla çalışmak geliştiriciler
```suggestion
Bu siyah ekran veya pencere, bilgisayarınızın sizin için çalıştıracağı komutları girebileceğiniz <span id="command-line">komut satırı arayüzüdür (CLI)</span>. Komut satırıyla çalışmak geliştiriciler için öğrenilmesi önemli bir beceridir. Komut satırı, diğer programları başlatabileceğimiz ve onlarla iletişime geçebileceğimiz operasyon üssü gibidir. Öğrenilmesi gereken kendine has bir sözdizimi vardır ancak aynı komutları onlarca kez gireceğiniz için ihtiyacınız olan komutları çabuk öğrenebileceksiniz.
```

2023-08-17 00:20 UTC, ubsoydan commented on temel_bilgiler/kurulumlar/komut_satiri_temelleri.md
> +Komut satırına giriş niteliğindeki bu derste, bilgisayarınızda nasıl gezineceğinizi ve doğrudan komut satırının rahatlığıyla dosya ve dizinleri (klasörler olarak da bilinir) nasıl değiştireceğinizi ö
```suggestion
Komut satırına giriş niteliğindeki bu derste, bilgisayarınızda nasıl gezineceğinizi ve doğrudan komut satırının rahatlığıyla dosya ve dizinleri (klasörler olarak da bilinir) nasıl değiştireceğinizi öğreneceksiniz. Bunun sandığınız kadar zor olmadığını göreceksiniz. Bu derste öğreneceğiniz komutlar çok basittir. Bu nedenle, komut satırını ilk kez kullanmak sizi korkutmasın.
```

2023-08-17 00:20 UTC, ubsoydan commented on temel_bilgiler/kurulumlar/komut_satiri_temelleri.md
> +1. Software Carpentry Foundation tarafından tasarlanan [The Unix Shell](https://swcarpentry.github.io/shell-novice/) kursuna göz atın. Orada CLI kullanımı ile ilgili tüm dersleri bulabilirsiniz, anca
```suggestion
1. Software Carpentry Foundation tarafından tasarlanan [The Unix Shell](https://swcarpentry.github.io/shell-novice/) kursuna göz atın. Orada CLI kullanımı ile ilgili tüm dersleri bulabilirsiniz ancak şimdilik, sadece aşağıdaki dersleri tamamlamaya odaklanalım:
```

2023-08-17 00:20 UTC, ubsoydan commented on temel_bilgiler/kurulumlar/komut_satiri_temelleri.md
> +Programcılar hakkında bilmeniz gereken önemli bir şey var. Programcılar bir şeyi yapmanın kolay yolunu ararlar. Gerçekten. Bir şeyi tekrar tekrar yapmaya zorlandıklarında, bunun yerine otomatikleştir
```suggestion
Programcılar hakkında bilmeniz gereken önemli bir şey var. Programcılar daima bir şeyi yapmanın kolay yolunu ararlar. Gerçekten. Bir şeyi tekrar tekrar yapmak zorunda kaldıklarında, büyük ihtimalle bunu otomatikleştirmenin bir yolunu bulacaklardır. İyi haber şu ki, programcıların bu güne kadar oluşturdukları birçok kısayoldan yararlanabileceksiniz. Komut satırını bir profesyonel gibi kullanmayı öğrenmenin zamanı geldi (yani, kısayollarla kolay bir şekilde).
```

2023-08-17 00:20 UTC, ubsoydan commented on temel_bilgiler/kurulumlar/komut_satiri_temelleri.md
> +Bu bölüm ilgili içeriklere yararlı bağlantılar içerir. Bu içeriklere bakmanız zorunlu değildir, ancak ilave olarak bunlara da bakmanızı tavsiye ediyoruz.
```suggestion
Bu alanda içerikle alakalı faydalı linkler bulunmaktadır. Zorunlu değildir, ek olarak düşünülmelidir.
```

2023-08-17 00:20 UTC, ubsoydan commented on temel_bilgiler/kurulumlar/komut_satiri_temelleri.md
> +- [Learn Enough Command Line to Be Dangerous](https://www.learnenough.com/command-line-tutorial) adlı çevrimiçi kitap, komut satırında uzmanlaşmak için harika bir kaynaktır. Bölüm 1 ve 2 ücretsizdir
```suggestion
- [Learn Enough Command Line to Be Dangerous](https://www.learnenough.com/command-line-tutorial) adlı çevrimiçi kitap, komut satırında uzmanlaşmak için harika bir kaynaktır. Bölüm 1 ve 2 ücretsizdir ve komut satırı araçlarına iyi bir giriş sağlar. Kitabın geri kalanı ücretsiz değildir ve bu noktada gerçekten ihtiyacınız olandan daha fazla derinliğe iner ancak ilginizi çekerse kitabın geri kalanını satın almaktan ve okumaktan çekinmeyin.
```

2023-08-17 00:20 UTC, ubsoydan commented on temel_bilgiler/kurulumlar/komut_satiri_temelleri.md
> +- [What is the command line?](#command-line)
```suggestion
- [Komut satırı nedir?](#command-line)
```

2023-08-17 00:20 UTC, ubsoydan commented on temel_bilgiler/kurulumlar/komut_satiri_temelleri.md
> +- [How do you open the command line on your computer?](#open-command-line)
```suggestion
- [Bilgisayarınızda komut satırını nasıl açarsınız?](#open-command-line)
```

2023-08-17 00:20 UTC, ubsoydan commented on temel_bilgiler/kurulumlar/komut_satiri_temelleri.md
> +- [How can you navigate to a particular directory?](https://www.softcover.io/read/fc6c09de/unix_commands/basics#sec-basics-cd)
```suggestion
- [Belirli bir dizine nasıl girersiniz?](https://www.softcover.io/read/fc6c09de/unix_commands/basics#sec-basics-cd)
```

2023-08-17 00:20 UTC, ubsoydan commented on temel_bilgiler/kurulumlar/komut_satiri_temelleri.md
> +- [Where will `cd` on its own navigate you to?](https://www.softcover.io/read/fc6c09de/unix_commands/basics#uid31)
```suggestion
- [Tek başına `cd` sizi nereye yönlendirir?](https://www.softcover.io/read/fc6c09de/unix_commands/basics#uid31)
```

2023-08-17 00:20 UTC, ubsoydan commented on temel_bilgiler/kurulumlar/komut_satiri_temelleri.md
> +- [Where will `cd ..` navigate you to?](https://www.softcover.io/read/fc6c09de/unix_commands/basics#uid30)
```suggestion
- [`cd ..` sizi nereye yönlendirir?](https://www.softcover.io/read/fc6c09de/unix_commands/basics#uid30)
```

2023-08-17 00:20 UTC, ubsoydan commented on temel_bilgiler/kurulumlar/komut_satiri_temelleri.md
> +- [How do you display the name of the directory you are currently in?](https://www.softcover.io/read/fc6c09de/unix_commands/basics#sec-basics-pwd)
```suggestion
- [Şu anda bulunduğunuz dizinin ismini nasıl gösterirsiniz?](https://www.softcover.io/read/fc6c09de/unix_commands/basics#sec-basics-pwd)
```

2023-08-17 00:20 UTC, ubsoydan commented on temel_bilgiler/kurulumlar/komut_satiri_temelleri.md
> +- [How do you display the contents of the directory you are currently in?](https://www.softcover.io/read/fc6c09de/unix_commands/basics#sec-basics-ls)
```suggestion
- [Şu anda bulunduğunuz dizinin içeriklerini nasıl gösterirsiniz?](https://www.softcover.io/read/fc6c09de/unix_commands/basics#sec-basics-ls)
```

2023-08-17 00:20 UTC, ubsoydan commented on temel_bilgiler/kurulumlar/komut_satiri_temelleri.md
> +- [How do you create a new directory?](https://www.softcover.io/read/fc6c09de/unix_commands/basics#cid7)
```suggestion
- [Yeni bir dizin nasıl yaratılır?](https://www.softcover.io/read/fc6c09de/unix_commands/basics#cid7)
```

2023-08-17 00:20 UTC, ubsoydan commented on temel_bilgiler/kurulumlar/komut_satiri_temelleri.md
> +- [How do you create a new file?](https://swcarpentry.github.io/shell-novice/03-create.html#create-a-text-file)
```suggestion
- [Yeni bir dosya nasıl oluşturulur?](https://swcarpentry.github.io/shell-novice/03-create.html#create-a-text-file)
```

2023-08-17 00:20 UTC, ubsoydan commented on temel_bilgiler/kurulumlar/komut_satiri_temelleri.md
> +- [How do you create a new file?](https://swcarpentry.github.io/shell-novice/03-create.html#create-a-text-file)
```suggestion
- [Yeni bir dosya nasıl oluşturulur?](https://swcarpentry.github.io/shell-novice/03-create.html#create-a-text-file)
```

2023-08-17 00:20 UTC, ubsoydan commented on temel_bilgiler/kurulumlar/komut_satiri_temelleri.md
> +- [How do you destroy a directory or file?](https://www.softcover.io/read/fc6c09de/unix_commands/basics#cid9)
```suggestion
- [Bir dizin veya dosya nasıl silinir?](https://www.softcover.io/read/fc6c09de/unix_commands/basics#cid9)
```

2023-08-17 00:20 UTC, ubsoydan commented on temel_bilgiler/kurulumlar/komut_satiri_temelleri.md
> +- [How do you rename a directory or file?](https://www.softcover.io/read/fc6c09de/unix_commands/basics#cid10)
```suggestion
- [Bir dizin veya dosya nasıl yeniden adlandırılır?](https://www.softcover.io/read/fc6c09de/unix_commands/basics#cid10)
```

2023-08-18 12:16 UTC, merged