Translate "Intro to css"
kamp-us/turkce-odin-project pull request #43
Opened 2023-09-06 04:49 UTC by emredevsalot

2023-12-24 21:50 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +### Derse Genel Bakış
```suggestion
### Derse genel bakış
```

2023-12-24 21:53 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +Bu bölüm, bu derste öğreneceğiniz konulara genel bir bakış içerir.
```suggestion
Bu bölüm, bu derste öğreneceğiniz konuların genel bir özetini içerir.
```

2023-12-24 21:54 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +- CSS ile HTML'e stiller ekleyin.
```suggestion
- CSS ile HTML'e stiller eklemek.
```

2023-12-24 21:54 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +- Class ve ID niteliklerinin nasıl kullanılacağını anlayın.
```suggestion
- Class ve ID niteliklerinin nasıl kullanılacağını anlamak.
```

2023-12-24 21:54 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +- Doğru seçicileri kullanarak belirli öğelere stiller ekleyin.
```suggestion
- Doğru seçicileri kullanarak belirli öğelere stiller eklemek.
```

2023-12-24 22:30 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +
```suggestion
```
This link is updated and moved to the end of this file.

2023-12-24 22:34 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +- [Mozilla CSS değerleri ve birimleri](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units) mutlak veya göreli olarak mümkün olan çeşitli değer türlerini öğrenmek için
```suggestion
- [Mozilla CSS değerleri ve birimleri](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units) mutlak veya göreli olarak mümkün olan çeşitli değer türlerini öğrenmek için kullanılabilir.
- [Bu ingilizce interaktif Scrim](https://scrimba.com/scrim/co12d4cf99cf2776f19e84a9d) dersteki materyallerin çoğunu interaktif bir biçimde ele almaktadır.
```

2023-12-24 22:34 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +### Temel Sözdizimi
```suggestion
### Temel sözdizimi
```

2023-12-24 22:37 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +#### Evrensel Seçici
```suggestion
#### Evrensel seçici
```

2023-12-24 22:38 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +#### Tip Seçiciler
```suggestion
#### Tip seçiciler
```

2023-12-24 22:42 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +#### Sınıf Seçiciler
```suggestion
#### Class seçiciler
```

2023-12-24 22:43 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +Sınıf seçiciler, aynı sınıfa(HTML öğelerine verilen niteliklerden biri) sahip tüm HTML öğelerini seçerler. Bir HTML öğesine nasıl sınıf ekleyeceğiniz ve bu sınıfı CSS'te nasıl seçeceğiniz aşağıda açı
```suggestion
Class(sınıf) seçiciler, aynı sınıfa(HTML öğelerine verilen niteliklerden biri) sahip tüm HTML öğelerini seçerler. Bir HTML öğesine nasıl class ekleyeceğiniz ve bu class'ı CSS'te nasıl seçeceğiniz aşağıda açıklanmıştır:
```

2023-12-24 22:44 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +Sınıf seçicilerin sözdizimine dikkat edin. Bir nokta ve hemen ardından hedeflenen sınıfın büyük/küçük harfe duyarlı değeri olarak kullanılır. Sınıfların belirli bir öğeye özel olması gerekmez. Bu ned
```suggestion
Class seçicilerin sözdizimine dikkat edin. Bir nokta ve hemen ardından hedeflenen sınıfın büyük/küçük harfe duyarlı değeri olarak kullanılır. Class'ların belirli bir öğeye özel olması gerekmez. Bu nedenle aynı class'ı istediğiniz sayıda öğeye ekleyebilirsiniz.
```

2023-12-24 22:45 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +Sınıflarla yapabileceğiniz bir başka şey ise tek bir öğeye birden fazla sınıfı aralarında boşluk bırakarak liste halinde eklemektir. Örneğin `class="alert-text severe-alert"` şeklinde kullanabilirsin
```suggestion
Class'larla yapabileceğiniz bir başka şey ise tek bir öğeye birden fazla class'ı aralarında boşluk bırakarak liste halinde eklemektir. Örneğin `class="alert-text severe-alert"` şeklinde kullanabilirsiniz. Class'ları ayırmak amacıyla boşluk kullanıldığı için, birden fazla kelimeyle tanımlanabilecek class'ların isimlerinde asla boşluk kullanmamalı, bunun yerine kısa çizgi kullanılmalıdır.
```

2023-12-24 22:45 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +#### ID Seçiciler
```suggestion
#### ID seçiciler
```

2023-12-24 22:45 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +ID seçiciler sınıf seçicilere benzer. HTML öğelerinin başka bir niteliği olan ID'ye sahip bir öğeyi seçerler. Sınıflar ve ID'ler arasındaki en büyük fark, bir öğenin yalnızca **bir** ID'ye sahip olab
```suggestion
ID seçiciler class seçicilere benzer. HTML öğelerinin başka bir niteliği olan ID'ye sahip bir öğeyi seçerler. Class'lar ve ID'ler arasındaki en büyük fark, bir öğenin yalnızca **bir** ID'ye sahip olabilmesidir. Bir sayfada tekrarlanamaz ve adında herhangi bir boşluk içermemelidir:
```

2023-12-24 22:49 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +ID'ler için nokta yerine hashtag kullanılır. Hemen ardından ID'nin büyük/küçük harfe duyarlı değeri gelir. Sıkça yapılan bir hata, insanların ihtiyaç duymadığı ve sınıfların yeterli olacağı durumlard
```suggestion
ID'ler için nokta yerine hashtag kullanılır. Hemen ardından ID'nin büyük/küçük harfe duyarlı değeri gelir. Sıkça yapılan bir hata, insanların ihtiyaç duymadığı ve class'ların yeterli olacağı durumlarda ID özelliğini aşırı kullanmasıdır. ID kullanmanın anlamlı veya gerekli olduğu durumlar olsa da(örneğin, özgüllüğün avantajından yararlanmak veya bağlantıların geçerli sayfadaki bir bölüme yönlendirmesi) onları **idareli** kullanmalısınız.
```

2023-12-24 22:49 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +  /* bu sınıfa özel tanımlamalar */
```suggestion
  /* bu class'a özel tanımlamalar */
```

2023-12-24 22:50 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +  /* bu sınıfa özel tanımlamalar */
```suggestion
  /* bu class'a özel tanımlamalar */
```

2023-12-24 22:50 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +  /* bu sınıfa özel tanımlamalar */
```suggestion
  /* bu class'a özel tanımlamalar */
```

2023-12-24 22:50 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +  /* bu sınıfa özel tanımlamalar */
```suggestion
  /* bu class'a özel tanımlamalar */
```

2023-12-24 22:51 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +Yukarıdaki örneklerin her ikisi de (gruplandırmalı ve gruplandırmasız) aynı sonuca sahip olacaktır. Ancak ikinci örnek, tanımlamaların tekrarını azaltır ve her iki sınıf için `color` ve `background-c
```suggestion
Yukarıdaki örneklerin her ikisi de (gruplandırmalı ve gruplandırmasız) aynı sonuca sahip olacaktır. Ancak ikinci örnek, tanımlamaların tekrarını azaltır ve her iki class için `color` ve `background-color`ın aynı anda düzenlenmesini kolaylaştırır.
```

2023-12-24 22:52 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +#### Soydan Gelen Birleştirici
```suggestion
#### Soydan gelen birleştirici
```

2023-12-24 22:53 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +Yukarıdaki örnekte, `contents` sınıfına sahip ilk iki öğe (B ve C) seçilecektir. Ancak son öğe (D) seçilmeyecektir. Tahmininiz doğru muydu?
```suggestion
Yukarıdaki örnekte, `contents` class'ına sahip ilk iki öğe (B ve C) seçilecektir. Ancak son öğe (D) seçilmeyecektir. Tahmininiz doğru muydu?
```

2023-12-24 22:54 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +Bir kurala kaç tane birleştirici ekleyebileceğiniz konusunda net bir sınır yoktur. Bu nedenle `.one .two .three .four` tamamen geçerli olacaktır. Bu seçim, `four` sınıfına sahip öğeyi ancak `three` s
```suggestion
Bir kurala kaç tane birleştirici ekleyebileceğiniz konusunda net bir sınır yoktur. Bu nedenle `.one .two .three .four` tamamen geçerli olacaktır. Bu seçim, `four` class'ına sahip öğeyi ancak `three` class'ına sahip bir atası varsa, o atanın `two`, onun atasının da `one` class'ına sahip öğesi varsa seçecektir. Genellikle bu seviyede iç içe geçmeye ihtiyaç duyan öğeleri seçmeye çalışmaktan kaçınmak isteriz. Çünkü oldukça kafa karıştırıcı ve uzun olabilirler. Özgüllük konusunda sorunlara da neden olabilirler.
```

2023-12-24 23:01 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +
```suggestion
```
This is also removed.

2023-12-24 23:04 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +Bir alfa değeri ekleyerek bu renklerin opaklığını nasıl ayarlayabileceğinizi görmek için [CSS Yasal Renk Değerleri](https://www.w3schools.com/cssref/css_colors_legal.asp) adresine hızlıca göz atın.
```suggestion
Bir alfa değeri ekleyerek bu renklerin opaklığını nasıl ayarlayabileceğinizi görmek için [CSS Legal Color Values](https://www.w3schools.com/cssref/css_colors_legal.asp) adlı ingilizce makaleye göz atın.
```

2023-12-24 23:07 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +#### Satır İçi CSS
```suggestion
#### Satır içi CSS
```

2023-12-24 23:09 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +1.  [CSS alıştırmaları repository'mize](https://github.com/TheOdinProject/css-exercises) gidin, README dosyasını okuyun ve `01-css-methods` ile başlayıp `05-descendant-combinator` ile bitecek şekilde
```suggestion
1.  [Odin Project CSS alıştırmaları repository'sine](https://github.com/TheOdinProject/css-exercises) gidin, README dosyasını okuyun ve `01-css-methods` ile başlayıp `05-descendant-combinator` ile bitecek şekilde `foundations` dizinindeki alıştırmaları sırasıyla yapın.
```

2023-12-24 23:09 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +### Bilgi Ölçme
```suggestion
### Bilgi ölçme
```

2023-12-24 23:10 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +Bu bölüm, dersi anlayıp anlamadığınızı kontrol etmeniz için sorular içermektedir. Bir soruyu yanıtlamakta zorlanıyorsanız, soruya tıklayıp yönlendirdiği materyali inceleyin.
```suggestion
Bu bölüm, bu dersi kendi kendinize anlayıp anlamadığınızı kontrol etmeniz için sorular içermektedir. Bir soruyu yanıtlamakta zorlanıyorsanız, soruya tıklayın ve bağlantılı olduğu materyali gözden geçirin.
```

2023-12-24 23:39 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +- <a class="knowledge-check-link" href="#external-css">HTML'e CSS eklemenin üç yöntemi arasındaki temel farklar nelerdir?</a>
```suggestion
- [Sınıf ve ID seçiciler için sözdizimi nasıldır?](#class-selectors)
- [Tek bir kuralı iki farklı seçiciye nasıl uygularsınız?](#the-grouping-selector)
- [ID'si `title` ve sınıfı `primary` olan bir öğe verildiğinde, tek bir CSS kuralı için her iki niteliği nasıl kullanırsınız?](#chaining-selectors)
- [Soydan gelen birleştirici ne işe yarar?](#descendant-combinator-description)
- [HTML'e CSS eklemek için kullanılan üç yöntemin isimleri nelerdir?](#adding-css-to-html)
- [HTML'e CSS eklemenin üç yöntemi arasındaki temel farklar nelerdir?](#external-css)
```

2023-12-24 23:39 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +### Ek Kaynaklar
```suggestion
### Ek kaynaklar
```

2023-12-24 23:43 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +  <link rel="stylesheet" href="styles.css" />
```suggestion
  <link rel="stylesheet" href="styles.css">
```
This is removed from original file.

2023-12-24 23:46 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +Bir tarayıcı, listedeki ilk yazı tipini bulamazsa veya onu desteklemiyorsa, desteklenen ve geçerli bir yazı tipi bulana kadar listeden sonraki tiplerini deneyerek devam eder. Bu nedenle, en çok kulla
```suggestion
Bir tarayıcı, listedeki ilk yazı tipini bulamazsa veya onu desteklemiyorsa, desteklenen ve geçerli bir yazı tipi bulana kadar listeden sonraki tiplerini deneyerek devam eder. Bu nedenle, en çok kullanılmasını istediğiniz yazı tipiyle başlayıp, yedek olarak genel bir yazı tipi ailesiyle biten bir liste oluşturmak en iyisidir, örneğin `font-family: "Times New Roman", serif;`
```
Update from original file

2023-12-24 23:51 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +~~~css
```suggestion
```css
```

2023-12-24 23:56 UTC, huseyingulec requested changes
Thank you Emre, good job. I only tried to check updates from original file and make some changes in this file. 

Very last thing, we have [this commit](https://github.com/TheOdinProject/curriculum/commit/f041518794c3637d825654db400ea9d149f3e4d7), somehow it kept ignoring my comments when updating backticks. Can you do that for me?

2023-12-25 14:22 UTC, emredevsalot commented
Thanks @huseyingulec 

I tried to do the changes related to code blocks here in this commit: https://github.com/kamp-us/turkce-odin-project/pull/43/commits/b23e6b46c57eb81ad5f4851b20bbc5a2081408e1 , can you check it out as well?

2023-12-25 15:13 UTC, huseyingulec commented
Thank you @emredevsalot, everything look great!. Thank you for all!!

2023-12-25 15:13 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +
```suggestion
```

2023-12-25 15:14 UTC, huseyingulec commented on temel_bilgiler/html_css/css-e-giris.md
> +#### Class(sınıf) seçiciler
```suggestion
#### Sınıf(class) seçiciler
```

2023-12-25 15:14 UTC, merged