docs: Translated from English to Turkish "css_units"
kamp-us/turkce-odin-project pull request #72
Opened 2023-12-05 13:57 UTC by alpererdogan8

`intermediate_css_concepts` başlığı altındaki `css_units`'i çevirdim

2023-12-06 14:24 UTC, huseyingulec requested changes

2023-12-06 14:24 UTC, hueypov commented on intermediate_html_css/intermediate_css_concepts/css_units.md
> +CSS'de boyutları tanımlamak için kullanabileceğiniz birçok farklı birim vardır. Bu ders sizin için en önemli olanları tanıtacak ve geri kalanı hakkında nereden öğrenebileceğinizi gösterecektir.
```suggestion
CSS'de boyutları tanımlamak için kullanabileceğiniz birçok farklı birim vardır. Bu ders sizin için en önemli olanları tanıtacak ve geri kalanları nereden öğrenebileceğinizi gösterecektir.
```

2023-12-06 14:24 UTC, hueypov commented on intermediate_html_css/intermediate_css_concepts/css_units.md
> +Mutlak birimler, herhangi bir bağlamda her zaman aynı olan birimlerdir. `px` mutlak bir birimdir çünkü bir pikselin boyutu sayfadaki başka hiçbir şeye göre değişmez. Aslında `px` web projeleri için k
```suggestion
Mutlak birimler, herhangi bir bağlamda her zaman aynı olan birimlerdir. `px` mutlak bir birimdir çünkü bir pikselin boyutu sayfadaki başka bir şeye göre değişmez. Aslında `px` web projeleri için kullanmanız gereken tek mutlak birimdir. Diğerleri `in` (inç) ve `cm` (santimetre) gibi fiziksel birimlerle ilişkili oldukları için baskı ortamında daha anlamlıdır.
```

2023-12-06 14:24 UTC, hueypov commented on intermediate_html_css/intermediate_css_concepts/css_units.md
> +`em` ve `rem` her ikisi de bir yazı tipi boyutunu ifade eder, genellikle CSS'de diğer boyutları tanımlamak için kullanılırlar. Her ikisini de sık sık göreceksiniz, bu yüzden her ikisini de açıklayaca
```suggestion
`em` ve `rem` genellikle CSS'de diğer boyutları tanımlamak için kullanılsalar da, her ikisi de bir yazı tipi boyutunu ifade eder. Her ikisini de sık sık göreceksiniz, bu yüzden her ikisini de açıklayacağız, ancak genel bir kural olarak `rem`'i tercih edin.
```

2023-12-06 14:24 UTC, hueypov commented on intermediate_html_css/intermediate_css_concepts/css_units.md
> +`1em` bir öğenin (veya `font-size` ayarlamak için kullanıyorsanız öğenin ebeveyninin) `font-size` değeridir. Örneğin, bir öğenin `font-size` değeri `16px` ise, genişliğini `4em` olarak ayarlamak geni
```suggestion
`1em` bir öğenin (veya `font-size` ayarlamak için kullanıyorsanız öğenin ebeveyninin) `font-size` değeridir. Örneğin, bir öğenin `font-size` değeri `16px` ise, öğenin genişliğini `4em` olarak ayarlamak genişliğini `64px` yapacaktır (`16 * 4 == 64`).
```

2023-12-06 14:24 UTC, hueypov commented on intermediate_html_css/intermediate_css_concepts/css_units.md
> +1. [CSS values and units](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units) mevcut tüm birimleri kapsar.
```suggestion
1. [CSS values and units](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Values_and_units) adlı ingilizce makale mevcut tüm birimleri kapsar.
```

2023-12-06 14:24 UTC, huseyingulec commented on intermediate_html_css/intermediate_css_concepts/css_units.md
> +2. Makale [CSS units](https://codyloyd.com/2021/css-units/) nasıl ve ne zaman `em`, `rem` veya `px` kullanmak isteyebileceğinizi derinlemesine açıklar.
```suggestion
2. [CSS units](https://codyloyd.com/2021/css-units/) adlı ingilizce makale nasıl ve ne zaman `em`, `rem` veya `px` kullanabileceğinizi derinlemesine açıklar.
```

2023-12-06 14:24 UTC, huseyingulec commented on intermediate_html_css/intermediate_css_concepts/css_units.md
> +3. [Fun with Viewport Units](https://css-tricks.com/fun-viewport-units/) `vh` ve `vw` ile yapabileceğiniz bazı ilginç şeyleri gösterir.
```suggestion
3. [Fun with Viewport Units](https://css-tricks.com/fun-viewport-units/) adlı ingilizce makale `vh` ve `vw` ile yapabileceğiniz bazı ilginç şeyleri gösterir.
```

2023-12-06 14:24 UTC, huseyingulec commented on intermediate_html_css/intermediate_css_concepts/css_units.md
> +Bu bölüm, bu dersi anladığınızı kontrol etmeniz için sorular içermektedir. Aşağıdaki soruları kendi başınıza yanıtlamakta zorlanıyorsanız, yanıtı bulmak için yukarıdaki materyali gözden geçirin.
```suggestion
Bu bölüm, bu dersi anladığınızı kontrol etmeniz için sorular içermektedir. Aşağıdaki soruları kendi kendinize yanıtlamakta zorlanıyorsanız, yanıtı bulmak için yukarıdaki materyali gözden geçirin.
```

2023-12-06 14:24 UTC, huseyingulec commented on intermediate_html_css/intermediate_css_concepts/css_units.md
> +- [Göreli bir birim yerine `px` kullanmak isteyebileceğiniz bazı durumlar nelerdir?](https://codyloyd.com/2021/css-units/)
```suggestion
- [Göreli bir birim yerine `px` kullanmak isteyebileceğiniz bazı durumlar nelerdir? bunu öğrenmek için bu ingilizce makaleye göz atın.](https://codyloyd.com/2021/css-units/)
```

2023-12-06 14:24 UTC, huseyingulec commented on intermediate_html_css/intermediate_css_concepts/css_units.md
> +Bu bölüm diğer içeriklere yararlı bağlantılar içerir. Gerekli değildir, bu nedenle bir konuda daha derine inmeniz gerektiğinde tamamlayıcı olarak düşünün.
```suggestion
Bu alanda içerikle alakalı faydalı linkler bulunmaktadır. Zorunlu değildir, bu nedenle bir şeyi daha derinlemesine incelemeniz gerektiğinde bunu tamamlayıcı olarak düşünün.
```

2023-12-06 14:24 UTC, huseyingulec commented on intermediate_html_css/intermediate_css_concepts/css_units.md
> +* Farklı durumlar için doğru CSS birimlerini seçme konusunda Kevin Powells'ın genel kurallarını öğrenmek istiyorsanız [are you using the right CSS unit?](https://www.youtube.com/watch?v=N5wpD9Ov_To).
```suggestion
* Farklı durumlar için doğru CSS birimlerini seçme konusunda Kevin Powells'ın genel kurallarını öğrenmek istiyorsanız [are you using the right CSS unit?](https://www.youtube.com/watch?v=N5wpD9Ov_To) adlı ingilizce videosunu izleyin. 
```

2023-12-06 14:26 UTC, huseyingulec commented
Teşekkür ederim @alpererdogan8,

Değişiklik isteklerimin çoğu küçük kelime eklemeleri/çıkarmaları, onlar dışında her şey çok güzel olmuş. Emeklerine sağlık, teşekkürler tekrar.

2023-12-06 15:59 UTC, alpererdogan8 commented
Merhaba @huseyingulec, revizelerin için teşekkür ederim eline sağlık.
İlgili düzenlemeleri yaptım.

2023-12-07 10:23 UTC, alpererdogan8 reviewed
İlgili değişiklileri yaptım.

2023-12-07 15:50 UTC, huseyingulec commented
Teşekkürler @alpererdogan8 , ellerine sağlık tekrardan.

2023-12-07 15:50 UTC, merged