Translate inspecting html and css
kamp-us/turkce-odin-project pull request #8
Opened 2023-05-08 20:16 UTC by emredevsalot

2023-05-08 20:39 UTC, sevilayerkan commented on temel_bilgiler/html_css/html-ve-css-inceleme/html-ve-css-inceleme.md
> +[Resmi Chrome Geliştiri Araçları dökümanının](https://developers.google.com/web/tools/chrome-devtools) aşağıdaki bölümlerini inceleyin:
There is a small mistype in `Geliştiri` it should be `Geliştirici`

2023-05-08 20:42 UTC, sevilayerkan commented on temel_bilgiler/html_css/html-ve-css-inceleme/html-ve-css-inceleme.md
> +- [Overview](https://developer.chrome.com/docs/devtools/overview/): burada bağlantısı verilen diğer sayfalara gitmeyin; Şimdi hepsini nasıl kullanacağınızdan ziyade DevTools'ta _hangi_ araçların mevc
Word that comes after `;` should start with a lowercase letter.

2023-05-30 00:09 UTC, cansirin requested changes

2023-05-30 00:09 UTC, cansirin commented on temel_bilgiler/html_css/html-ve-css-inceleme/html-ve-css-inceleme.md
> +Bu bölüm, bu derste öğreneceğiniz konulara genel bir bakış içerir.
```suggestion
Bu bölüm, bu derste öğreneceğiniz konuların genel bir özetini içerir.
```

2023-05-30 00:09 UTC, cansirin commented on temel_bilgiler/html_css/html-ve-css-inceleme/html-ve-css-inceleme.md
> +- [This article about how we can utilize css overview in the developer tools](https://www.freecodecamp.org/news/how-to-use-css-overview-in-chrome-developer-tools/) to check the colors, font styles, m
Don't we need translation for here?

2023-05-30 00:09 UTC, cansirin commented on temel_bilgiler/html_css/html-ve-css-inceleme/html-ve-css-inceleme.md
> +<span id="strikethrough">Bir öğe seçildiğinde, Stiller sekmesi, uygulanmakta olan tüm stillerin yanı sıra üzerine yazılan stilleri de gösterir (metnin üstü çizili olarak gösterilir).</span> Örneğin,
```suggestion
<span id="strikethrough">Bir öğe seçildiğinde, Stiller bölmesi, uygulanmakta olan tüm stillerin yanı sıra üzerine yazılan stilleri de gösterir (metnin üstü çizili olarak gösterilir).</span> Örneğin, ana sayfadaki "Web Geliştirme Kariyeriniz Burada Başlıyor" başlığına tıklamak için denetçiyi kullanırsanız, aşağıda görüldüğü gibi, sağ tarafta şu anda öğeyi etkileyen tüm stilleri göreceksiniz.
```

2023-07-18 18:31 UTC, merged